name: Gabriel Abner Coppini
description: Desenvolvedor  

markdown: kramdown
highlighter: rouge
plugins:
    - jekyll-paginate
paginate: 15
baseurl: /
domain_name: 'http://gcoppini.github.com'
google_analytics: 'UA-135160919-1'

# Details for the RSS feed generator
url: 'http://gcoppini.github.com'

author:
    name: Gabriel Abner Coppini
    thumb: /assets/images/profile.jpg
    bio: Desenvolvedor tolo
    url:
        site: 'http://gcoppini.github.io'
        github: 'https://github.com/gcoppini'
        facebook: 'https://www.facebook.com/gabriel.coppini.3'
        twitter: 'https://twitter.com/coppinigabriel'
        linkedin: 'https://br.linkedin.com/in/gabrielcoppini'
        stackoverflow: 'https://stackoverflow.com/users/2150415/user2150415'
        email: 'gabriel.coppini(at)gmail.com'

urls:
    about: /sobre

img_path: /assets/images/